export const ERROR_MSG = {
  GAME_OVER: 'GAME_OVER',
  INVALID_ACTION: 'INVALID_ACTION',
  BALANCE_INSUFFICIENT: 'BALANCE_INSUFFICIENT',
  INVALID_BET_AMOUNT: 'INVALID_BET_AMOUNT',
  INVALID_RAISE_AMOUNT: 'INVALID_RAISE_AMOUNT',
  GAME_IS_RUNNING: 'GAME_IS_RUNNING',
};

export enum ActionType {
  FOLD = 'FOLD',
  CHECK = 'CHECK',
  BET = 'BET',
  RAISE = 'RAISE',
}
